extends: metric
message: "The grade level is %s. Aim for 8th grade or lower by using shorter sentences and words."
level: suggestion
formula: |
  (0.39 * (words / sentences)) + (11.8 * (syllables / words)) - 15.59
condition: "> 1"